name: 'CI'
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4         # checkout the repo
        with:
          submodules: recursive
      - run: |
            make
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4         # checkout the repo
        with:
          submodules: recursive
      - run: |
            make test