name: 'CI'
on:
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4         # checkout the repo
        with:
          submodules: recursive
      - uses: ruby/setup-ruby@v1       # setup ruby environment
        with:
          ruby-version: '3.0'
      - run: |
            make test | tee report.txt
            ruby ./ext/Unity/auto/parse_output.rb -xml report.txt
      - uses: actions/upload-artifact@v4  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results
          path: report.xml